apiVersion: apps/v1
kind: Deployment
metadata:
  name: shashmitha-react
spec:
  selector:
    matchLabels:
      app: shashmitha-react
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: shashmitha-react
    spec:
      containers:
      - name: react-app
        image: shashmitha2001/react-docker-aws-deploy:v1
        ports:
        - containerPort: 80
